source $BASHER/src/MILD_SECRETS/SUPER_SECRETS/super_secret_aliases
source ~/.platform/aliases
source $BASHER/src/git/git_aliases

#alias python
# alias python='python3'

#Mac aliases
alias pbcopy='xclip -select clipboard'

#conda-related aliases
alias cact='conda activate'
alias cdct='conda deactivate'
alias clst='conda env list'

#git-related aliases
alias gp='git push'
alias ga='git add'
alias gc='git commit'
alias gau='git add -u'
alias gst='git status'
alias gsl='git status -uno'
alias gb='git branch'
alias gls='ls $(git ls-files)'
alias gcm='git commit -m'
alias gl='git log'
alias gla='git log --oneline --graph --all'
alias gch='git checkout'
alias gcn='git clean -n'
alias gdy='git difftool -y'
alias glc='git log --oneline --graph --decorate --all'
alias gcg='git config --global'
alias ggg='git config --global --get'
alias grh='git reset --hard'
alias grp='git rev-parse'
alias grc='git rebase --continue'

#screensaver
alias scrsv='xscreensaver-command -activate'

#ssh
alias start_agent='eval "$(ssh-agent -s)"'

#vim
alias vi='vim'

#sudo store shortcut
alias sur='su root'

#alias check_jail
alias blist='mudo $(which python3) $BASHER/src/py_scripts/check_jail.py'

# alias ch="python $BASHER/src/py_scripts/chydra.py"

# alias for ". .latest" for IOMT
alias aa='. .latest'

#qmake
alias qmake="/home/tyler/miniconda3/envs/qt/lib/qt6/bin/qmake"
declare -A cxa=(
    ['r']="$REPO"
    ['b']="$BASHER/src"
    ['i']="$ISL"
    ['pys']="$BASHER/src/py_scripts"
    ['pl']="$BASHER/src/platform"
)
